# by Sisi Liu: sisi.liu@awi.de | sisi.liu.research@gmail.com (permanent address)
# R version 4.2.2 (2022-10-31)
# Platform: aarch64-apple-darwin20 (64-bit)
# Running under: macOS Ventura 13.1

#== Ancient DNA damage pattern: Fig. S3 and Fig. S4
# Post-processing: 3 steps for accuracy in taxonomic read assignment and ancient authentication criteria
# Note: a greater number of damaged reads (> 100) is required for reliable edit distance evaluation due to the fact that not all ancient reads are expected to exhibit damage.
library(readr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(ggdist)

#== create folders
dir.create("step03_assigned/01_damage/outTables")
dir.create("step03_assigned/01_damage/outFigures")

#== ngs id
ngs="APMG-5-10-28-34-35"

#== sample list (infor. in Table S6)
sampleid=read.csv(paste0("NC-sampleList-NGS.csv"), stringsAsFactors = F, row.names = 1)
names(sampleid)
names(sampleid)=c("fasteris", "sample","sampleR", "age", "ex", "lib")
sampleid=sampleid[!is.na(sampleid$age), ]

#== import txt files generated by maltExtract
data00=NULL
for (sample in sampleid$fasteris) {
  print(sample)
  # default/edit
  edit0=read.delim(file = paste0("me_po/", sample, "/maltExtract/default/editDistance/", sample, "_fastp_merged_R2.rma6_editDistance.txt"), 
                   header = T, sep = "\t", check.names = F)
  names(edit0)[-1]=paste0("default_", names(edit0)[-1])
  # damageMismatch
  damageMismatch=read.delim(file = paste0("me_po/", sample, "/maltExtract/default/damageMismatch/", sample, "_fastp_merged_R2.rma6_damageMismatch.txt"), header = T, sep = "\t")
  damageMismatch=damageMismatch[c(1:11, 22:31)]
  # ancient/edit
  edit1=read.delim(file = paste0("me_po/", sample, "/maltExtract/ancient/editDistance/", sample, "_fastp_merged_R2.rma6_editDistance.txt"), 
                   header = T, sep = "\t", check.names = F)
  names(edit1)[-1]=paste0("ancient_", names(edit0)[-1])
  # readDist
  readLengthDist=read.delim(file = paste0("me_po/", sample, "/maltExtract/default/readDist/", sample, "_fastp_merged_R2.rma6_readLengthDist.txt"), header = T, sep = "\t")
  # table
  df=cbind(edit0, edit1[-1], damageMismatch[-1], readLengthDist[-1])
  #
  df$fasteris=sample
  df$sample=sampleid[sampleid$fasteris==sample, "sample"]
  df$sampleR=sampleid[sampleid$fasteris==sample, "sampleR"]
  df$age=sampleid[sampleid$fasteris==sample, "age"]
  df$lib=sampleid[sampleid$fasteris==sample, "lib"]
  df$ex=sampleid[sampleid$fasteris==sample, "ex"]
  df=df %>%
    select("fasteris", "sample", "sampleR", "age", "lib", "ex", everything())
  #
  data00=rbind(data00, df)
}
data00$Taxon=gsub("_", " ", data00$Taxon)

#== 3-steps-post-processing: negative_delta_percent == 1 (corrected assigned), damaged reads >= 100, negative_delta_percent == 1 (damaged reads)
mytag=c("Bos mutus", "Saxifraga sinomontana", "Asteraceae", "Asteroideae", "Salix",  "Saliceae", 
        "Potamogeton perfoliatus", "Nannochloropsis limnetica")

plots=list()
if (TRUE) {
  for (i in mytag) {
    print(i)
    df=data00[data00$Taxon == i, ]
    # ancient_0 ..+.. ancient_10 >= 100
    df$ancient_sum=rowSums(df[, 20:31])
    df=df[df$ancient_sum >= 100, ]
    # edit distance should be reduced
    df$edit_dis=df$default_0-df$default_1
    df=df[df$edit_dis > 0, ]
    ctmax=0.3
    if (nrow(df) > 0) {
      for (j in 1:nrow(df)) {
        df01=df[j, ]
        age=df01$age
        # edit distance
        edit0=seq(0, 5)
        reads0=df01[, 8:13]
        # C>T
        position=seq(1,10)
        ct=df01[1, 32:41]
        dv=df01[1, 42:51]
        rownames(dv)="1"
        # ancient 
        edit1=seq(0, 5)
        reads1=df01[, 20:25]
        # length
        bp=seq(30, 200, 5)
        len=df01[, 53:87]
        # plots
        mydata1=data.frame(x=edit0, y=t(reads0))
        names(mydata1)=c("x", "y")
        #== negative delta percent (== 1)
        # Define the read counts at each edit distance category
        read_counts <- mydata1$y
        # Calculate the differences (Δ)
        delta <- -diff(read_counts)
        # Calculate -Δ%
        negative_delta_percent <- sum(delta[delta>0])/sum(abs(delta))
        negative_delta_percent=round(negative_delta_percent, digits = 1)
        # plot 1: edit distance of default
        p1=ggplot(data = mydata1, aes(x=x, y=y)) +
          scale_x_continuous(name = "Edit distance: default", breaks = seq(0, 5, 1)) +
          scale_y_continuous("Number of reads") +
          geom_bar(stat = "identity") +
          theme_bw() +
          theme(axis.text = element_text(color = "black", size = 6),
                axis.title = element_text(color = "black", size = 6))
        # plot 2: C>T
        mydata2=data.frame(x=position, y=t(ct), z=t(dv))
        names(mydata2)=c("x", "y", "z")
        p2=ggplot(data = mydata2) +
          scale_x_continuous(name = "Position in read", breaks = seq(0, 10, 1)) +
          scale_y_continuous("Rate of C>T substitutions", limits = c(0, ctmax)) +
          geom_line(aes(x=x, y=y), color="red") +
          geom_line(aes(x=x, y=z), color="grey70") +
          theme_bw() +
          theme(axis.text = element_text(color = "black", size = 6),
                axis.title = element_text(color = "black", size = 6))
        # plot 3: post-assessment 
        # edit distance distribution for damaged reads and thus all reads harbor by definition at least one mismatch. 
        # note: > 100 is required for reliable edit distance evaluation due to the fact that not all ancient reads are expected to exhibit damage.
        mydata3=data.frame(x=edit1, y=t(reads1))
        names(mydata3)=c("x", "y")
        p3=ggplot(data = mydata3, aes(x=x, y=y)) +
          scale_x_continuous(name = "Edit distance: ancient", breaks = seq(0, 5, 1)) +
          scale_y_continuous("Number of reads") +
          geom_bar(stat = "identity") +
          theme_bw() +
          theme(axis.text = element_text(color = "black", size = 6),
                axis.title = element_text(color = "black", size = 6))
        #
        figure=annotate_figure(ggarrange(p1, p2, p3, nrow = 1, align = "h"),
                               top = text_grob(paste0(i, ": ", age, " ka"), color = "black", face = "bold", size = 6))
        plots[[paste0(i, "-", age)]]=figure
      } 
    } else {
      next
    }
    
  }
}
ggsave(paste0("step03_assigned/01_damage/outFigures/Combined_damage.pdf"), width = 29, height = 21, units = "cm",
       marrangeGrob(grobs=plots, nrow=5, ncol=3, top = NULL, layout_matrix = matrix(1:15, 5, 3, TRUE)))

#== assess age-dependent signal 
mytag=c("Bos mutus", "Asteraceae", "Salix",  "Saxifraga sinomontana", "Asteroideae", "Saliceae", 
        "Potamogeton perfoliatus", "Nannochloropsis limnetica")
df=data00[data00$Taxon %in% mytag, ]
# pre-14 ka
tempdf=df[df$age > 14, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf=tempdf[tempdf$anc_sum >= 100, ]
tempdf$diff=tempdf$default_0-tempdf$default_1
tempdf=tempdf[tempdf$diff > 0, ]
#
df_long=melt(tempdf[, c(4, 7, 32:51)], id.vars=c("age", "Taxon"))
df_long$position=rep(1:10, times=2, each=nrow(tempdf))
df_long$cat=c(rep("ct", nrow(tempdf)*10), rep("dv", nrow(tempdf)*10))
df_long=df_long[order(df_long$Taxon, df_long$variable), ]

# ct
ctdf=df_long[df_long$cat == "ct", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- ctdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- ctdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
ctdf=cbind(mean_values, sd_values[, 3])

dvdf=df_long[df_long$cat == "dv", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- dvdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- dvdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
dvdf=cbind(mean_values, sd_values[, 3])
#
# The palette:
#palette1 <- c("darkolivegreen3", "firebrick2", "dodgerblue2", "gold1", "deeppink","darkgreen", "darkorange", "darkorchid4")
palette1 <- c("#006633", "#333399", "#FFCC33", "#CC99CC", "#CC9966", "#CCFFCC", "#FF0033", "#99CCFF")
taxa1=c("Bos mutus", "Saxifraga sinomontana", "Asteraceae", 
        "Nannochloropsis limnetica", 
        "Potamogeton perfoliatus", "Asteroideae", "Salix", "Saliceae")
# Create color mapping
color_mapping <- setNames(palette1, taxa1)
#
p1 <- ggplot() +
  scale_x_continuous("Read position", breaks = seq(1, 10, 1)) +
  scale_y_continuous("Rate of C to T substitutions", limits = c(0, 0.3), breaks = seq(0, 0.3, 0.05)) +
  geom_point(data = ctdf, aes(x=position, y = mean_value, color = Taxon), show.legend = F, size = .6) +
  geom_errorbar(data = ctdf, aes(x=position, ymin = mean_value - sd_value, ymax = mean_value + sd_value, color = Taxon), 
                width = 0.3, show.legend = F) +
  geom_line(data = ctdf, aes(x=position, y = mean_value, color = Taxon), show.legend = F, size = .3) +
  #
  geom_point(data = dvdf, aes(x=position, y = mean_value, color = Taxon), alpha = 0.5, 
             show.legend = F, size = .6) +
  geom_line(data = dvdf, aes(x=position, y = mean_value, color = Taxon), alpha = 0.2, 
            linetype="dashed", show.legend = F, size = .3) +
  scale_color_manual(values = color_mapping) +
  scale_fill_manual(values = color_mapping) +
  ggtitle("Pre-14 ka")+
  theme_bw() +
  theme(legend.position = "top", 
        plot.title = element_text(color = "black", size = 8),
        axis.text = element_text(color = "black", size = 8),
        axis.title = element_text(color = "black", size = 8))

# 14-3.6 ka
df=data00[data00$Taxon %in% mytag, ]
tempdf=df[df$age > 3.6 & df$age < 14, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf=tempdf[tempdf$anc_sum >= 100, ]
#
df_long=melt(tempdf[, c(4, 7, 32:51)], id.vars=c("age", "Taxon"))
df_long$position=rep(1:10, times=2, each=34)
df_long$cat=c(rep("ct", 340), rep("dv", 340))
df_long=df_long[order(df_long$Taxon, df_long$variable), ]

# ct
ctdf=df_long[df_long$cat == "ct", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- ctdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- ctdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
ctdf=cbind(mean_values, sd_values[, 3])

dvdf=df_long[df_long$cat == "dv", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- dvdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- dvdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
dvdf=cbind(mean_values, sd_values[, 3])
#
p2 <- ggplot() +
  scale_x_continuous("Read position", breaks = seq(1, 10, 1)) +
  scale_y_continuous("Rate of C to T substitutions", limits = c(0, 0.3), breaks = seq(0, 0.3, 0.05)) +
  geom_point(data = ctdf, aes(x=position, y = mean_value, fill = Taxon, color = Taxon), size = .6, show.legend = F) +
  geom_errorbar(data = ctdf, aes(x=position, ymin = mean_value - sd_value, ymax = mean_value + sd_value, color = Taxon), 
                width = 0.3, show.legend = F) +
  geom_line(data = ctdf, aes(x=position, y = mean_value, color = Taxon), size = .3, show.legend = F) +
  #
  geom_point(data = dvdf, aes(x=position, y = mean_value, fill = Taxon, color = Taxon), alpha = 0.5, size = .6, show.legend = F) +
  geom_line(data = dvdf, aes(x=position, y = mean_value, color = Taxon), alpha = 0.2, 
            linetype="dashed", size = .3, show.legend = F) +
  scale_color_manual(values = color_mapping) +
  scale_fill_manual(values = color_mapping) +
  #geom_errorbar(data = dvdf, aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), width = 0.2) +
  ggtitle("14-3.6 ka")+
  theme_bw() +
  theme(legend.position = "top", 
        plot.title = element_text(color = "black", size = 8),
        axis.text = element_text(color = "black", size = 8),
        axis.title = element_text(color = "black", size = 8))

# post-3.6
df=data00[data00$Taxon %in% mytag, ]
tempdf=df[df$age < 3.6, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf=tempdf[tempdf$anc_sum >= 100, ]
#
df_long=melt(tempdf[, c(4, 7, 32:51)], id.vars=c("age", "Taxon"))
df_long$position=rep(1:10, times=2, each=2)
df_long$cat=c(rep("ct", 20), rep("dv", 20))
df_long=df_long[order(df_long$Taxon, df_long$variable), ]

# ct
ctdf=df_long[df_long$cat == "ct", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- ctdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- ctdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
ctdf=cbind(mean_values, sd_values[, 3])

dvdf=df_long[df_long$cat == "dv", ]
# Calculate mean and SD values for each taxon and position using dplyr
mean_values <- dvdf %>% group_by(Taxon, position) %>% summarize(mean_value = mean(value))
sd_values <- dvdf %>% group_by(Taxon, position) %>% summarize(sd_value = sd(value))
dvdf=cbind(mean_values, sd_values[, 3])
#
p3 <- ggplot() +
  scale_x_continuous("Read position", breaks = seq(1, 10, 1)) +
  scale_y_continuous("Rate of C to T substitutions", limits = c(0, 0.3), breaks = seq(0, 0.3, 0.05)) +
  geom_point(data = ctdf, aes(x=position, y = mean_value, fill = Taxon, color = Taxon), size = .6, show.legend = F) +
  geom_errorbar(data = ctdf, aes(x=position, ymin = mean_value - sd_value, ymax = mean_value + sd_value, color = Taxon), 
                width = 0.3, show.legend = F) +
  geom_line(data = ctdf, aes(x=position, y = mean_value, color = Taxon), size = .3, show.legend = F) +
  #
  geom_point(data = dvdf, aes(x=position, y = mean_value, fill = Taxon, color = Taxon), alpha = 0.5, size = .6, show.legend = F) +
  geom_line(data = dvdf, aes(x=position, y = mean_value, color = Taxon), alpha = 0.2, 
            linetype="dashed", size = .3, show.legend = F) +
  scale_color_manual(values = color_mapping) +
  scale_fill_manual(values = color_mapping) +
  #geom_errorbar(data = dvdf, aes(ymin = mean_value - sd_value, ymax = mean_value + sd_value), width = 0.2) +
  ggtitle("Post-3.6 ka")+
  theme_bw() +
  theme(legend.position = "top", 
        plot.title = element_text(color = "black", size = 8),
        axis.text = element_text(color = "black", size = 8),
        axis.title = element_text(color = "black", size = 8))
# p3

# correlation
# pre-14 ka
df=data00[data00$Taxon %in% mytag, ]
tempdf=df[df$age > 14, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf=tempdf[tempdf$anc_sum >= 100, ]
tempdf$diff=tempdf$default_0-tempdf$default_1
tempdf01=tempdf[tempdf$diff > 0, ]
# 14-3.6
df=data00[data00$Taxon %in% mytag, ]
tempdf=df[df$age > 3.6 & df$age < 14, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf02=tempdf[tempdf$anc_sum >= 100, ]
# post-3.6
df=data00[data00$Taxon %in% mytag, ]
tempdf=df[df$age < 3.6, ]
rownames(tempdf)=seq(1, nrow(tempdf))
tempdf$anc_sum=rowSums(tempdf[, 20:31])
tempdf03=tempdf[tempdf$anc_sum >= 100, ]
#
#ct_cols <- colnames(df)[grepl("^C.T_", colnames(df))]
tempdf=rbind(tempdf01[c("age", "C.T_1")], tempdf02[c("age", "C.T_1")], tempdf03[c("age", "C.T_1")])
tempdf_long=melt(tempdf, "age")
#
p4=ggplot(tempdf_long, aes(x = age, y = value)) +
  scale_x_reverse("Age / cal ka BP", breaks = seq(18, 0, -1)) +
  scale_y_continuous("Rate of C to T substitutions") +
  geom_point() +
  labs(x = "X", y = "Y") +
  # Add a GLM line of best fit
  geom_smooth(method = "glm", method.args = list(family = gaussian(link = "identity")), 
              formula = y ~ x, se = T) + 
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
    label.x = -9, label.y = 0.3) +
  ggtitle("GLM(deamination rates ~ age)")+
  theme_bw() +
  theme(legend.position = "top", 
        plot.title = element_text(color = "black", size = 8),
        axis.text = element_text(color = "black", size = 8),
        axis.title = element_text(color = "black", size = 8))
p4

#== save
pdf(file = paste0("step03_assigned/01_damage/outFigures/CT_cor_Time.pdf"), width = 5, height = 10)
print(ggarrange(p1, p2, p3, p4, nrow = 4, align = "v"))
dev.off()
#== end ==






